services:
  app:
    build: 
      context: ./docker-ffmpeg
      dockerfile: Dockerfile
    image: node-ffmpeg:latest
    ports:
     - "3006:3000"
    env_file:
     - .env
    deploy:
      resources:
        limits:
          cpus: '2' 
          memory: 20g 