services:
  app:
    build: .
    image: node-ffmpeg:latest
    ports:
     - "3005:3000"
    env_file:
     - .env
    deploy:
      resources:
        limits:
          cpus: '2' 
          memory: 5g 
        